name: Cypress
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node:version: '14'
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v2

      - name: Copy test execution videos
        run: |
          mkdir public
          cp -r cypress/videos public/videos
          - name: Merge test results into one
            run: npm run report:merge
          - name: Generate HTML report
            run: npm run report:generate
          - name: Output the run Details
                  uses: actions/upload-artifact@v2
                  with:
                    name: UI-Test-Results
                    path: testResults