# This is a basic workflow to help you get started with Actions

name: K6 Local

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: "./LoadTest/K6-script.js"

        - name: Upload html report for job 1
            uses: actions/upload-artifact@v2
            with:
              #html file name define in k6 code
              name: summary
              # path in our github repo
              path: summary.html
              # available time period file after that is automatically remove from the workspace
              retention-days: 2